version: '3.9'

services:

    simple-web-service:
      image: devopsdockeruh/simple-web-service
      build: .
      volumes:
        - ./log:/usr/src/app/text.log
      container_name: simple-web-service
