version: "3.9"

services:
  example-backend:
    container_name: example-backend
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
  example-frontend:
    container_name: example-frontend
    build: ./example-frontend
    ports:
      - 5001:5000
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
