version: '3.9'

services:

    simple-web-service:
      image: devopsdockeruh/simple-web-service
      build: .
      ports:
            - 8080:8080
      container_name: simple-web-service
      command: ["server"]
